name: Deploy Projects

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout javascript-projects
        uses: actions/checkout@v5

      - name: Prepare deployment
        run: |
          mkdir deploy

          cp -r 001-qr-code-component deploy/
          cp -r 002-blog-preview-card deploy/
          cp -r 003-social-links-profile deploy/
          cp -r 004-recipe-page deploy/

      - name: Deploy to ncticn.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: ncticn/ncticn.github.io
          publish_branch: main
          publish_dir: ./deploy
